name: {{cookiecutter.repo_name}}
channels:
  - https://repo.anaconda.com/pkgs/snowflake
 
dependencies:
  - {{ cookiecutter.python_interpreter }}
  - snowflake-snowpark-python
  - snowflake-ml-python
  - pandas
  - scikit-learn
  - statsmodels
  - pycaret
  - matplotlib
  - seaborn
  - bokeh
  - modin
  - numpy
  - scipy
  - pathlib
  - pcre2
  - pandas-profiling
  - pip
  - python-dotenv
  - pip:
    - jupyterlab
    - black
  # Add more dependencies as needed
